### ISSUE TITLE
在x86、arm启动后出现网页返回Forbidden的情况

### ISSUE THREAD

**Issue by FUjr** [dadaxiaoxiaod/JDC#7]
x86与arm的机器都是非跑青龙的局域网内机器，分别尝试用root和其他用户启动过
已复制青龙auth.json到报错指向的目录
客户端一切正常
![image](https://user-images.githubusercontent.com/53910283/125357661-802f8a00-e39a-11eb-9ed6-24c0aaffbef0.png)
网页显示如图
![image](https://user-images.githubusercontent.com/53910283/125357678-86be0180-e39a-11eb-8d13-56d642d43a59.png)
修改过配置文件如图
![image](https://user-images.githubusercontent.com/53910283/125357783-ac4b0b00-e39a-11eb-911c-975f1938aa57.png)
自己复制下来的密码文件内容如图
![image](https://user-images.githubusercontent.com/53910283/125357865-c684e900-e39a-11eb-8707-16026aaa3f18.png)

**Comment by FUjr** [comment]
![image](https://user-images.githubusercontent.com/53910283/125358416-70647580-e39b-11eb-811c-75ee7ef45480.png)
漏了个青龙面板版本号～

**Comment by dadaxiaoxiaod** [comment]
web文件放上去了吗

**Comment by FUjr** [comment]
不好意思，第一次用jdc，之前的文档也找不到了，可以说下是什么web文件吗？感谢

**Comment by FUjr** [comment]
jdc-web吗，放进去了，现在好了，我是水货，打扰大佬了
